export default {
    "scripts": {
      "start": "graphql-codegen && snowpack dev",
      "dev": "snowpack dev",
      "build": "graphql-codegen && snowpack build",
      "test": "jest",
      "generate": "graphql-codegen",
      "svelte-check": "svelte-check",
      "cy:open": "cypress open"
    },
    "devDependencies": {
      "@graphql-codegen/cli": "^1.15.0",
      "@graphql-codegen/import-types-preset": "^1.15.4",
      "@graphql-codegen/typescript-document-nodes": "^1.15.3",
      "@graphql-codegen/typescript-graphql-request": "^1.15.3",
      "@graphql-codegen/typescript-operations": "^1.15.0",
      "@snowpack/app-scripts-svelte": "^1.0.6",
      "@snowpack/plugin-webpack": "^1.1.0",
      "@testing-library/jest-dom": "^5.5.0",
      "@testing-library/svelte": "^3.0.0",
      "cypress-daywalker": "^0.2.1",
      "cypress-plugin-tab": "^1.0.5",
      "cypress-svelte-unit-test": "^3.2.0",
      "jest": "^25.4.0",
      "mdi-svelte": "^1.1.1",
      "rollup-plugin-graphql-tag": "^0.1.0",
      "snowpack": "^2.0.0",
      "svelte": "^3.24.0",
      "svelte-check": "^0.1.37",
      "svelte-preprocess": "^3.9.7",
      "typescript": "^3.9.5"
    },
    "dependencies": {
      "@fullcalendar/core": "^4.4.2",
      "@fullcalendar/daygrid": "^4.4.2",
      "@fullcalendar/interaction": "^4.4.2",
      "@fullcalendar/list": "^4.4.2",
      "@fullcalendar/timegrid": "^4.4.2",
      "@material/mwc-button": "^0.15.0",
      "@material/mwc-checkbox": "^0.15.0",
      "@material/mwc-dialog": "^0.15.0",
      "@material/mwc-drawer": "^0.15.0",
      "@material/mwc-fab": "^0.15.0",
      "@material/mwc-icon-button": "^0.15.0",
      "@material/mwc-icon-button-toggle": "^0.15.0",
      "@material/mwc-linear-progress": "^0.15.0",
      "@material/mwc-list": "^0.15.0",
      "@material/mwc-menu": "^0.15.0",
      "@material/mwc-select": "^0.15.0",
      "@material/mwc-snackbar": "^0.15.0",
      "@material/mwc-tab": "^0.15.0",
      "@material/mwc-tab-bar": "^0.15.0",
      "@material/mwc-textarea": "^0.15.0",
      "@material/mwc-textfield": "^0.15.0",
      "@material/mwc-top-app-bar": "^0.15.0",
      "@mdi/js": "^5.3.45",
      "@urql/svelte": "^0.2.3",
      "graphql": "^15.0.0",
      "moment": "^2.27.0",
      "svelte-i18n": "^3.0.4",
      "sveltejs-tippy": "^3.0.0"
    }
  }